# Generated by Django 4.1.3 on 2022-12-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_feedback_customer_customer_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
    ]
